### ISSUE TITLE
Paypal-here-Sdk is not getting initialized on any device 

### ISSUE THREAD

**Issue by AbdulSalamAli0018** [paypal/paypal-here-sdk-android-distribution#105]
I have installed the Demo app on my android device but it looks like that every time I tried to run app the sdk gets failed to initialized . I tried doing it different way but using OAuth web api. but after getting tokem and When I tried to get the Sdk initialized I got the same error. I do not know what is the real problem . 

It states me the bellow problem : 
**initializeSDK setCredentialsFromCompositeStr onError error: com.paypal.merchant.sdk.domain.PPError@29db261** 

I do not know what is the error and real problem behind it. I am working from Pakistan whereas Our App has a paypal merchant account setup and getting payments successful there in USA but that is using another swipper and we only using the API

But here all I need is to use my Paypal here swipper which plugs into the audio jack . All I want is that get the SDK initialized so that I can get the track information.   and then do my processing in my own way 

Is that possible and what about my problem?????

**Comment by ppmtscory** [comment]
PayPal Here uses a third party token so you will need to follow the instructions [here](https://developer.paypal.com/docs/integration/paypal-here/merchant-onboarding/initiating-the-onboarding-flow/) to get the refresh token that you can store for your account and then use to generate the access token to pass into the SDK.  You'll then switch the demo app to use the `setCredentials` method and pass in the newly generated access token that you got from following the steps above.

Also, all of the swipe information is encrypted at the reader head so you won't be able to get the track data to process your own way.
