### ISSUE TITLE
Signature Screen Orientation

### ISSUE THREAD

**Issue by tkocik92** [paypal/paypal-here-sdk-android-distribution#109]
Is it possible to have the SDK signature screen in portrait instead of landscape? Our kiosk app is locked in portrait mode and this is the only SDK screen that does not follow that convention.

**Comment by ppmtscory** [comment]
At this time, no, there isn't a way to set the orientation of the signature screen portion of the SDK UI.  This was set to landscape to allow for a better user experience across various device/screen sizes.  I will record this feedback for consideration with any future releases, however.

**Comment by seankwalker** [comment]
Hi, any updates on this? This still seems to be an issue.

**Comment by ppmtscory** [comment]
There is `setReceiptScreenOrientation` that can be set as such: `RetailSDK.setReceiptScreenOrientation(ReceiptScreenOrientation.LANDSCAPE);`

**Comment by ppmtscory** [comment]
You aren't able to set the signature UI orientation, no, but you can set the receipt screen orientation if you'd like.  The signature screen is set with the orientation of the device.

**Comment by seankwalker** [comment]
gotcha. the signature screen is not reflecting the device orientation for us right now; is there any special configuration needed for it to do so?

**Comment by ppmtscory** [comment]
Are you using the latest version of the SDK?  What device are you using and what's the behavior you are seeing?

**Comment by seankwalker** [comment]
yep, version 2.1.03.19276000. It's on an ELO I-series 22"
when the device is rotated, our app which is using the Here SDK re-orients properly, but the signature screen after a payment goes through will render as portrait mode regardless of the device's orientation

**Comment by DowsingUK** [comment]
Can't the SDK just have an option to re-orientated the signature screen?
