### ISSUE TITLE
PayPal Here SDK Swiper Card Reader

### ISSUE THREAD

**Issue by heng-pcsp** [paypal/paypal-here-sdk-android-distribution#110]
Hi dear,
I used ionic framework for develop mobile app and used cordova plugin for integrate paypal here sdk with ionic.
I want swipe card information only, please help me
note: i'm not android developer

**Comment by ppmtscory** [comment]
We don't provide the swipe information alone.  This is encrypted information and the processing of said information is done within the SDK.
