### ISSUE TITLE
Authorize and Capture functionality

### ISSUE THREAD

**Issue by mithrasvs** [paypal/paypal-here-sdk-android-distribution#115]
Hi,

I am trying to build a software for restaurant and trying to implement authorizePayments & capturePayments. I couldn't find proper document about their usage.

Can you help me with that or point the the right place?

Currently, in chargeActivity.Java, after beginPayment() and initiateEMVTransaction(), instead of calling takePayment() and I am calling authorizePayment().

Error says, "No payment information provided in order to take a payment."

Help is much appreciated.

**Comment by mithrasvs** [comment]
@ppmtscory @amrish7 

can you please help me here?

**Comment by ppmtscory** [comment]
@mithrasvs you won't be able to do auth/capture with EMV transactions with the current 1.6.x SDK, unfortunately.  Therefore, you'll need to use the regular triangle magstripe swiper and, in the SDK, you'd call beginPayment() and then authorizePayment().  Our new SDK (v2) will have auth/capture available for EMV transactions shortly so if you're wanting that, then please stay tuned.

**Comment by ppmtscory** [comment]
No, you can use that reader, and auth/capture functionality with 1.6.10 which is on it's own branch in this repo.  The master branch will soon be updated to match with the release-2.0 branch.

**Comment by ppmtscory** [comment]
Auth/Capture code is available to review in the new sample app that's now included in this repo but the functionality is not completely tested/available on the backend yet.  Therefore, you can review the code to see how it will work, and I'll update here once the functionality is fully available on our backend.

**Comment by mithrasvs** [comment]
@ppmtscory Thank you for the update... I'll stay tuned

**Comment by ppmtscory** [comment]
@mithrasvs this auth/capture feature is now available for the US region.
