### ISSUE TITLE
Seeing java.lang.IllegalStateException: J2V8 native library not loaded runtime exception in 2.0 SDK

### ISSUE THREAD

**Issue by amrish7** [paypal/paypal-here-sdk-android-distribution#118]
2.0 version of SDK is throwing a `java.lang.IllegalStateException: J2V8 native library not loaded runtime exception on my App
```
java.lang.IllegalStateException:J2V8 native library not loaded.
java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[,nativeLibraryDirectories=[/data/app/com.gettaxi.dbx.android-1/lib/arm64, /data/app/com.gettaxi.dbx.android-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64] couldn't find "libj2v8.so"
```

**Comment by amrish7** [comment]
This is a known issue https://github.com/eclipsesource/J2V8/issues/174

The proposed work around is to add the following `ndk` support to `android.defaultConfig` of your App's build.gradle
```
android {
    ....
    defaultConfig {
        ....
        ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86", "mips"
        }
    }
}
```

**Comment by amrish7** [comment]
PayPal Here App uses this fix currently and it is working fine. Native 64 bit support for this SDK will come with an upcoming release

**Comment by Hypnoticbg** [comment]
For kotlin based gradle files you should change it to:

 //https://github.com/paypal/paypal-here-sdk-android-distribution/#installation
ndk {
     abiFilters.addAll(listOf("armeabi", "armeabi-v7a", "x86", "mips"))
}

**Comment by Bhing09** [comment]
Run
