### ISSUE TITLE
When connecting to device using connectToLastActiveReader(...), the callback is not called in some cases.

### ISSUE THREAD

**Issue by muhshan** [paypal/paypal-here-sdk-android-distribution#135]
This issue is reproducible with the paypal here sample application.

Step to reproduce the issue:
1. open the sample app and initialize the app, initialize the merchant and switch to the connection screen
2. Click "connect to last known device"
3. On the connection popup, click "Find another reader"
4. Select one of the paired device listed in the "Find another reader" popup
5. Notice on the device that the connection happened properly. Device displays "Ready to accept payment"

Expected result:
The provided observer (com.paypal.paypalretailsdk.DeviceManager.ConnectionCallback()) to the call connectToLastActiveReader(...) be called.

Actual result:
The provided observer (com.paypal.paypalretailsdk.DeviceManager.ConnectionCallback()) to the call connectToLastActiveReader(...) is never called.

Workaround: 
I'm not sure but, calling again connectToLastActiveReader(...) seems to trigger the call to the observer.

**Comment by djjames** [comment]
Y is not working

**Comment by Technickster** [comment]
Similar thing with the scanAndAutoConnectToBluetoothReader

**Comment by DJ92** [comment]
Hi @Technickster @muhshan ,

The autoConnect() callbacks have been fixed.

Please follow the code snippet as shown below:
```public void autoConnectLastReader() {
    String readerName = RetailSDK.getDeviceManager().getLastActiveBluetoothReader();
    if(readerName != null) {
      RetailSDK.getDeviceManager().scanAndAutoConnectToBluetoothReader(readerName, new DeviceManager.ConnectionCallback() {
        @Override
        public void connection(final RetailSDKException error, final PaymentDevice cardReader) {
          if (error != null) {
            // Find and connect
          }
          if (cardReader.isConnected()) {
            //Ready to accept payment
          }
        }
      });
    } else {
      // Find and connect
    }
  }
```
Thanks.
I'm closing this issue for now, but let me know if there are any open items regarding this.
