### ISSUE TITLE
Disable Receipt Options

### ISSUE THREAD

**Issue by legomanaustralia** [paypal/paypal-here-sdk-android-distribution#138]
Is there an ability to hide the receipt prompt for the paypal here inApp part? We have a specific use case where showing the receipt infers the application has completed and is confusing to users.

**Comment by DJ92** [comment]
Hi,
What merchant is this integration for? We are currently making a process to support hiding that feature and would need some info.

**Comment by legomanaustralia** [comment]
It's for www.gettoken.com - we do a rfid cashless payment system that uses Paypal here for taking topup payments initially, these are for a self serve portal however the paypal intitial/receipt makes it extremely confusing with "transction complete" etc as this is something we handle in the next step of the flow.

**Comment by vanceanderson41** [comment]
Hello, @DJ92 

We have a similar inquiry about receipts. We use PayPal Here among other payment processing services and have a custom receipt delivery system in place for all transactions recorded, so it's less than ideal to invariably show the receipt options screen after each transaction.

**Comment by DJ92** [comment]
Hey @nicernick ,

Glad to know about your integration. There's a way to suppress the receipts. Can you send me a mail at dhejoshi@paypal.com and I'll send the information on how to do that.

Thanks
