### ISSUE TITLE
App with Timber

### ISSUE THREAD

**Issue by nicernick** [paypal/paypal-here-sdk-android-distribution#143]
We use Timber in our application and have encountered a situation whereby our version appears to be interfering with the normal working of the SDK.
This is easily replicated in the Sample App by adding the following dependency
`implementation 'com.jakewharton.timber:timber:4.5.1'`
when this is added the `MerchantInitializedCallback` does not fire

We're looking at revising our use to move back to 2.5.1 which fixes the issue but this is less than ideal as we currently use functionality from the later version.
Any help would be much appreciated

**Comment by DJ92** [comment]
Hey @nicernick , I just added the dependency and built the app, all works fine. It probably be down to the gradle version you are using at the moment (I test this on 3.0.1). I'll need to see some logs to help you better @nicernick.

**Comment by nicernick** [comment]
Thanks, reverting to the older version of Gradle appears to have worked. We were using 4.4.
