### ISSUE TITLE
Taxes in Sandbox

### ISSUE THREAD

**Issue by tkocik92** [paypal/paypal-here-sdk-android-distribution#148]
I have implemented the latest version of the SDK (debug:2.1.0.201801) into my app. I have a sandbox merchant with sales tax set up. When I create my invoice, `getItemTax()` returns 0 and `getTotal()` returns the subtotal. If I manually add a tax rate to every invoice item, `getItemTax()` and `getTotal()` return the correct amounts.

When I begin the payment process and use a valid card for payment, the amount charged to the card is the subtotal, not the total. I cannot find how to charge for the total.

All of this is occurring in the Sandbox environment. Location permissions are granted (if that matters?). 

Can someone point me in the right direction to resolve these issues?

**Comment by DJ92** [comment]
Hey @tkocik92 , the item tax is set in the addItem or explicit method and only then can be retrieved using getItemTax(). As for the tax rate set inside the account, I don't believe there's a way to retrieve that from the SDK but does apply to the transaction as a subtotal. Does that answer or clear the confusion?

**Comment by tkocik92** [comment]
@DJ92 It clears up the confusion as to where I should set the tax rate for InvoiceItem's.

It does not resolve that beginning a payment only charges for the subtotal instead of the total (subtotal + tax).

**Comment by DJ92** [comment]
Hey @tkocik92,

For the latter, if you set something to default tax on the account, it'll apply to transactions processed automatically and will be visible on the receipts.

Hope that helps.
Thanks!

**Comment by tkocik92** [comment]
@DJ92 Is that true for Sandbox accounts? I set a tax rate for the entire US (for testing purposes) on the Sandbox account I am using and it was never getting applied (this was on sandbox.paypal.com). Or does this get set in the application somewhere?

**Comment by DJ92** [comment]
We've tested this on live. For sandbox, I might have to do some more digging to confirm if it actually applies it across the board. I'll keep it open and follow up.

**Comment by DJ92** [comment]
So I did some testing and these are my results:

The tax rate can be applied to items in the SDK Invoice creation logic. The overall tax rate in the sandbox account doesn't get picked up due to test environment limitations but it applies on live.
