### ISSUE TITLE
NullPointerException when calling RetailSDK.initializeMerchant

### ISSUE THREAD

**Issue by yxrwang** [paypal/paypal-here-sdk-android-distribution#156]
I was integrating the SDK into my app, unfortunately NullPointerException was immediately thrown when our app called RetailSDK.initializeMerchant method. 

Here is the detail stack trace:
java.lang.NullPointerException: Attempt to invoke virtual method 'com.paypal.manticore.JsExecutor com.paypal.manticore.ManticoreEngine.getExecutor()' on a null object reference
com.paypal.paypalretailsdk.RetailSDK.initializeMerchant(RetailSDK.java:277)

I am running my app on a HTC mobile which is running Android 5.1 (API 22). Could you help me to have a look at the issue?

Thanks

**Comment by DJ92** [comment]
Hey @yxrwang , can I get some more information around this ? What's the merchant, clientID and environment being used here? 

Thanks!
-Dheeraj

**Comment by yxrwang** [comment]
Hi Dheeraj,

Thanks for the reply. I was using sandbox environment, the merchant is dale-facilitator@batchandco.com.au, the client id is AaXgURBu8Okb1escxzeX-IOgsIQmmae81k5KkoxQbugHoWXOiPvihJ2ptu1c

Cheers,
Jack

**Comment by DJ92** [comment]
Can you try now @yxrwang ? Also, is there an AM assigned to you that you're working with from our side?

**Comment by yxrwang** [comment]
@DJ92 I tried just now, the same error. I don't think there is an AM assigned to me. Actually, this was working before about 2 months ago. I haven't changed anything.

**Comment by DJ92** [comment]
What is the SDK version you are using? Is this an integration in the AU?

**Comment by yxrwang** [comment]
Yes, it is in Australia. The SDK versions are 
api('com.paypal.retail:here-sdk-debug:2.1.0.201801@aar'){transitive=true}
api 'com.eclipsesource.j2v8:j2v8:4.6.0@aar'

**Comment by yxrwang** [comment]
Hey @DJ92 , after a serious investigation, there was a bug in my code where the RetailSDK was not initialised before initializeMerchant was called. 

I will close this issue, sorry for the confusion. Thanks for your support.
