### ISSUE TITLE
Is this an error in PayPal server or mine?

### ISSUE THREAD

**Issue by DowsingUK** [paypal/paypal-here-sdk-android-distribution#180]
After few weeks trying everything was working good but now I keep getting this error I have restart everything in my server so can somebody help me please, thank you

D/PayPalRetailSDK:paypalRest( 8306): POST https://api-m.sandbox.paypal.com/v1/retail/checkouts (9829ms): 500 
E/PayPalRetailSDK:paypalRest( 8306): Received error {
E/PayPalRetailSDK:paypalRest( 8306):   "errMessage": "domain: retail, code: 600000, message: An internal server error has occurred., Field=null, Issue=INTERNAL_SERVICE_ERROR, debugId: 4b07fdbf595db, details: "
E/PayPalRetailSDK:paypalRest( 8306): }
D/PayPalRetailSDK:flow.step.mtp( 8306): MTP response received from API retail/checkouts 
D/PayPalRetailSDK:flow.step.mtp( 8306): MTP response: {
D/PayPalRetailSDK:flow.step.mtp( 8306):     "statusCode": 500,
D/PayPalRetailSDK:flow.step.mtp( 8306):     "headers": {
D/PayPalRetailSDK:flow.step.mtp( 8306):         "cache-control": "max-age=0, no-cache, no-store, must-revalidate",
D/PayPalRetailSDK:flow.step.mtp( 8306):         "content-length": "275",
D/PayPalRetailSDK:flow.step.mtp( 8306):         "content-type": "application/json",
D/PayPalRetailSDK:flow.step.mtp( 8306):         "date": "Tue, 12 May 2020 17:11:27 GMT",
D/PayPalRetailSDK:flow.step.mtp( 8306):         "paypal-debug-id": "4b07fdbf595db",
D/PayPalRetailSDK:flow.step.mtp( 8306):         "x-slr-retry": "500",
D/PayPalRetailSDK:flow.step.mtp( 8306):         "x-slr-retry-api": "/v1/retail/checkouts"
D/PayPalRetailSDK:flow.step.mtp( 8306):     },
D/PayPalRetailSDK:flow.step.mtp( 8306):     "body": {
D/PayPalRetailSDK:flow.step.mtp( 8306):         "correlationId": "4b07fdbf595db",
D/PayPalRetailSDK:flow.step.mtp( 8306):         "errorCode": 600000,
D/PayPalRetailSDK:flow.step.mtp( 8306):         "errorType": "service_error",
D/PayPalRetailSDK:flow.step.mtp( 8306):         "message": "An internal server error has occurred., Field=null, Issue=INTERNAL_SERVICE_ERROR",
D/PayPalRetailSDK:flow.step.mtp( 8306):         "developerMessage": "An internal server error has occurred., Field=null, Issue=INTERNAL_SERVICE_ERROR"
D/PayPalRetailSDK:flow.step.mtp( 8306):     }
D/PayPalRetailSDK:flow.step.mtp( 8306): } 
E/PayPalRetailSDK:flow.step.mtp( 8306): MTPErr {
E/PayPalRetailSDK:flow.step.mtp( 8306):   "currency": "USD",
E/PayPalRetailSDK:flow.step.mtp( 8306):   "total": "1.23",
E/PayPalRetailSDK:flow.step.mtp( 8306):   "ff": 2,
E/PayPalRetailSDK:flow.step.mtp( 8306):   "isEmv": true,
E/PayPalRetailSDK:flow.step.mtp( 8306):   "err": "{\"code\":\"600000\",\"domain\":\"retail\",\"debugId\":\"4b07fdbf595db\"}",
E/PayPalRetailSDK:flow.step.mtp( 8306):   "status": 500,
E/PayPalRetailSDK:flow.step.mtp( 8306):   "resp": "{\"correlationId\":\"4b07fdbf595db\",\"errorCode\":600000,\"errorType\":\"service_error\",\"message\":\"An internal server error has occurred., Field=null, Issue=INTERNAL_SERVICE_ERROR\",\"developerMessage\":\"An internal server error has occurred., Field=null, Issue=INTERNAL_SERVICE_ERROR\"}"
E/PayPalRetailSDK:flow.step.mtp( 8306): }

**Comment by ppmtscory** [comment]
This was an issue in the sandbox environment earlier but I'm able to run successful transactions now so please give it another shot.

**Comment by DowsingUK** [comment]
I just try a second ago still having same problem

**Comment by DowsingUK** [comment]
It's working now!
