### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by inabdev30** [paypal/paypal-here-sdk-android-distribution#195]
Unable to build the sample app, facing this issue:

Execution failed for task ':compileDebugJavaWithJavac'.
java.lang.IllegalArgumentException: '_' may not be a valid Java identifier.

**Comment by inabdev30** [comment]
I just check the sample app again and still facing same issue, I attach the file containing complete stack trace please have a look.
[complete build logs.txt](https://github.com/paypal/paypal-here-sdk-android-distribution/files/7072322/complete.build.logs.txt)

**Comment by EarthyOrange** [comment]
@inabdev30 Can you please try building the sample app after removing the following from the build.gradle file?

    // Android Annotation

    annotationProcessor 'org.androidannotations:androidannotations:4.4.0'

    implementation 'org.androidannotations:androidannotations-api:4.4.0'

**Comment by inabdev30** [comment]
@EarthyOrange Yes, it is working fine now. Thank you.
