### ISSUE TITLE
Card reader timeout after processPaymentWithSDKUI call makes the view unresponsive

### ISSUE THREAD

**Issue by balage-amarasena** [paypal/paypal-here-sdk-android-distribution#69]
In PayPal here sdk sample app for android after the method processPaymentWithSDKUI is executed we see the dialog telling users to "Please tap, insert or swipe your card". if the user does not do any of these things for about ~20 seconds the card reader times out. The android app removes the above mentioned dialog and goes to a state where it seems to have set focus on some hidden dialog (The status bar on the top of the phone turns blue) and does not respond to any user interactions until the user presses the back button. (This seems to bring the focus back to the current view). Is there a way to avoid this weird behaviour. 

Ok FYI. the onContactlessReaderTimeout() method override allows us to Cancel or Retry when this happens and avoids the hidden blocked sample app scenario. Would be nice if the sample app had this code.

**Comment by ppmtscory** [comment]
Correct - the sample app is here to simply display the general functionality of a transaction with the PPH SDK and does not have _all_ possible scenarios implemented.  I've marked this as an enhancement so that it can be tracked for any future sample app updates.

**Comment by cdewberry** [comment]
I would like to be able to cancel swiping a card after calling PayPalHereSDK.getTransactionManager().beginPayment(amount, transactionController) and
processPaymentWithSDKUI
or
could someone please show the sequence of calls for providing my own UI and calling processPayment() - like which version of processPayment should I call to read a card swipe?

**Comment by ppmtscory** [comment]
With the EMV readers, you will need to use the UI included in the SDK.  There are enhancements being made to the new SDK that's available which will include allowing the modification of said UI and/or having the option to not use the UI at all.
