### ISSUE TITLE
Receipt screen text cut short when displayed on portrait tablet

### ISSUE THREAD

**Issue by JarredSteenvoorden** [paypal/paypal-here-sdk-android-distribution#73]
Testing the fix made for #62 (using PayPalHereSDK-1.6.2.6) on our tablet has found that while now the screen is rotating correctly for portrait orientation the text is cut off and not fully visible.

See the following screenshot that shows how it is displayed on a Nexus 7 and Pendo Pad 7 device:
https://drive.google.com/file/d/0B5_jGJprjCUWTDdsekJ5dEFLcjQ/view

It is however displayed correctly with a phone (Nexus 6):
https://drive.google.com/file/d/1Pv-jQqbqBrcgJ8xiAn05z0lc_qTZVZxC1w/view

You can on a tablet the full width is not used causing some texts fields to be cut short.

**Comment by ppmtscory** [comment]
@jarred-s thanks for following up with this report.  I will have a look and see if I can tell what's happening.

**Comment by ppmtscory** [comment]
If your issue persists, after updating to the newly released SDK, please either reopen or create a new issue with additional details.
