### ISSUE TITLE
Android 7 Nougat - Webview login issue 

### ISSUE THREAD

**Issue by developersteve** [paypal/paypal-here-sdk-android-distribution#85]
Currently the Webview throws and error and is unable to work on Android 7 Nougat with the SDK login links unable to connect..

`[ERROR:gles2_cmd_decoder.cc(2167)] [.CommandBufferContext.RenderCompositor 0x94219e00]GL ERROR :GL_INVALID_OPERATION : BackFramebuffer::Destroy: <- error from previous GL command`

**Comment by ppmtscory** [comment]
Please update to our newly released SDK and let us know if you run into any issues when using a webview.
