### ISSUE TITLE
PayPal here EMV reader connection issue

### ISSUE THREAD

**Issue by abhirav** [paypal/paypal-here-sdk-android-distribution#95]
Hi,
I am having issues with Paypal Reader EMV connection. I successfully getting SDK initialised but while connecting with reader it fails giving me SDK error dialog "Software Update Failed". Below are the steps I am doing to make Paypal HERE android sdk work with our apps:

1. Get authorization code:
Request: https://www.paypal.com/signin/authorize?scope=https://uri.paypal.com/services/paypalhere&response_type=code&redirect_uri=www.ourwebsite.com&client_id={client_id_from_paypal_developer_portal_app}
Response: I get authorisation_code

2. Get Token:
Request: /v1/identity/openidconnect/tokenservice?grant_type=authorization_code&code={authorisation_code}. I do pass -u{client_id:secret} as Basic 64 encoded
Response: access_token {A103.....}, expiresIN {28800}, refresh_token{R103.....}, and other valid json

3. Base Encode tokens with JSONArray:
                compositeToken = "sdk_token=live:" + Base64.encodeToString(array.toString().getBytes(), Base64.DEFAULT);

4. Successful Initialisation of SDK: PayPalHereSDKWrapper.getInstance().initializeSDK(getApplicationContext(), serverName, compositeToken, new PayPalHereSDKWrapperCallbacks() {
                .....
     @Override
                public void onSuccessfulCompletionOfSettingAccessTokenToSDK() {
                    // I AM HEREEE
                }
            });

4. While connecting to reader, it throws error:
 E/Volley: [5613] BasicNetwork.performRequest: Unexpected response code 500 for https://api-m.paypal.com/v1/retail/secure-terminal-config/MIURA/M010?environment=production&country=&os=M000-OS-7-6&mpi=M000-MPI-1-41&requester=sdk

Note: If I use access_token, from sample server URL, everything works fine, If I use access_token obtained by above procedure, the EMV reader tries to update software and then fails.

Could you please help me out here and tell me if I am doing something wrong here.
Abhi.

**Comment by ppmtscory** [comment]
Please update to the latest SDK as there has been improvements to this process.  Do let us know if you run into any issues.
