### ISSUE TITLE
PayPal Here SDK URI

### ISSUE THREAD

**Issue by kevintparker** [paypal/paypal-here-sdk-android-distribution#96]
PayPal Technical support forwarded me so I was hoping someone can give me an answer here. I am posting this on both Android and Apple PayPal SDK sites. 

Based on the documentation:
**_The PayPal Here SDK for iOS is a collection of classes, protocols, and other resources for developing point-of-sale apps that run in iOS. It communicates with the underlying PayPal APIs at the following URIs:
https://www.paypal.com/webapps/hereapi/merchant/v1               Live environment_**

A simple GET to this (properly passing oAuth access token)
https://www.paypal.com/webapps/hereapi/merchant/v1/invoices

returns the top 50 invoices and also a hasMoreResults set to false.

I assume that I can somehow get more than 50 results using some sort of filter. 

I have tried to POST using json, x-www-form-urlencoded, I have tried adding URL variables, nothing works. I get 400 Bad Request.

How can I filter to get more than 50?

**Comment by ppmtscory** [comment]
Closing this as it's going to be addressed via your other issue [here](https://github.com/paypal/paypal-here-sdk-ios-distribution/issues/109).
