### ISSUE TITLE
Activity Leak

### ISSUE THREAD

**Issue by PaulNeesham** [paypal/paypal-here-sdk-android-distribution#97]
Using 1.6.6

When Calling PayPalHereSDK.getCardReaderManager().connectToDevice().
Each time it fails to connect a new EMVDeviceConnectActivity Leaks. (5 leaks of this activity can be seen in the bump) 

When Calling PayPalHereSDK.getTransactionManager().processPaymentWithSDKUI().

The EMVPaymentActivity Leaks.

Also EMVDeviceUpdateActivity seems to have leaked when updating the device.

As you can see in the heap Dump:
[com.autocab.driverapp_2017.01.11_11.35.hprof.zip](https://github.com/paypal/paypal-here-sdk-android-distribution/files/698691/com.autocab.driverapp_2017.01.11_11.35.hprof.zip)

**Comment by ppmtscory** [comment]
@PaulNeesham can you let us know what device you're running this on and also what Android version?

**Comment by amrish7** [comment]
Hi @PaulNeesham - Thanks for reporting on this issue. I found out a couple of scenarios that caused the destroyed activity to not be reclaimed I am working on fixing it. 

Question - Wondering if there were any `out of memory` exceptions that lead you to this issue?

**Comment by PaulNeesham** [comment]
Here are 3 images from the bump:
![dump1](https://cloud.githubusercontent.com/assets/2102461/22056006/c4cbbbb6-dd55-11e6-82d6-7e8446b43123.PNG)
![dump2](https://cloud.githubusercontent.com/assets/2102461/22056007/c4cbeafa-dd55-11e6-99ca-ba4e7d16ca95.PNG)
![dump3](https://cloud.githubusercontent.com/assets/2102461/22056008/c4ce8a44-dd55-11e6-81a6-dfc92a76f5c6.PNG)

**Comment by PaulNeesham** [comment]
This was running on a Nexus 5X with Android 7, the reason I found it was just from noticing the memory usage was increasing over time for the app, I found an activity leak in my own code but also noticed the PayPal code was leaking.

**Comment by ppmtscory** [comment]
Please upgrade to the latest SDK and let us know if you run into any issues.
