### ISSUE TITLE
zlib dependency in server's package.json blocking heroku install

### ISSUE THREAD

**Issue by spencermwatts** [paypal/paypal-here-sdk-android-distribution#98]
Heroku won't deploy the sample server file unless the zlib dependency is removed.

This is because zlib is no longer maintained (as it is built into node.js).

**Comment by ppmtscory** [comment]
The sample_server that's included in this repo is no longer valid.  There's a PR to have it removed but it just hasn't been merged yet.  If you're wanting a sample server to use, please utilize our current one [here](https://github.com/paypal/paypal-retail-node).

**Comment by spencermwatts** [comment]
Thanks, @ppmtscory -- appreciate it.
